databases:
  - name: psql
    plan: free
    databaseName: psql_mufj
    user: psql_mufj_user

services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn djangorestsite.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: psql
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4