# Generated by Django 5.0.3 on 2024-06-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='release_year',
            field=models.IntegerField(),
        ),
    ]
